Tempus 1073 file upload linking new
hashmapinc/Tempus pull request #1097
Opened 2019-03-11 09:57 UTC by RachanaGupta01

Thank you for submitting a contribution to Tempus.

In order to streamline the review of the contribution please
ensure the following steps have been taken:

### For all changes:
- [ ] Is there a Waffle ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with Tempus-XXXX where XXXX is the waffle number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically dev)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn clean install at the root Tempus folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you added documentation for any UI or API related changes to the /docs folder

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

2019-03-11 12:12 UTC, anuj-akt requested changes

2019-03-11 12:12 UTC, anuj-akt commented on application/src/it/java/com/hashmapinc/server/controller/BaseUploadControllerTest.java
> +        Device device = createDevice();
Extract device creation in before test method

2019-03-11 12:12 UTC, anuj-akt commented on application/src/main/java/com/hashmapinc/server/controller/UploadController.java
> +            EntityId relatedEntityId = createRelatedEntityId(strRelatedEntityId, strRelatedEntityType);//getRelatedEntityId(strRelatedEntityId);
clean comment

2019-03-11 12:12 UTC, anuj-akt commented on application/src/main/java/com/hashmapinc/server/service/upload/UploadService.java
>  import com.hashmapinc.server.service.computation.CloudStorageService;
move it out of computation package

2019-03-11 12:12 UTC, anuj-akt commented on application/src/main/java/com/hashmapinc/server/service/upload/UploadService.java
> +        if (!oldObjectUrl.contentEquals(newObjectUrl) && cloudStorageService.copyFile(bucketName, oldObjectUrl, newObjectUrl)) {
update filemetadata in this case

2019-03-11 12:12 UTC, anuj-akt commented on application/src/main/java/com/hashmapinc/server/service/upload/UploadService.java
> +                    System.currentTimeMillis(),
refactor duplicate return metadta

2019-03-12 05:48 UTC, jayeshkapadnis approved these changes

2019-03-12 13:49 UTC, anuj-akt approved these changes

2019-03-12 15:17 UTC, merged